# -*- coding: utf-8 -*-
"""Image_Scrapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/159i-YDtTNYMu_fyNo5Rd_kfMjauvZgGm
"""

!pip install -q jmd_imagescraper

cd Colab\ Notebooks

from pathlib import Path
root = Path().cwd()/"images"

from jmd_imagescraper.core import * 

duckduckgo_search(root, "Kaira Advani", "kaira advani", max_results=300)

